import { JobApplication, Interview, SkillGap, AppNotification } from "../types";

export const MOCK_CANDIDATE_PROFILE = {
  name: "Sakhi",
  roleHeadline: "Backend Developer",
  skillsMeta: "Laravel, PHP, MySQL — 3 yrs experience — expects Rs 90,000/mo",
  isOpenToWork: true,
  completenessPercent: 72,
  completionHint: "Add 2 skills and a project to reach 90%",
  avatarText: "SK",
};

export const MOCK_CANDIDATE_KPIS = [
  { title: "Applications", value: "14", trendDelta: "3 active", trendDirection: "up" as const },
  { title: "Interviews Scheduled", value: "3", trendDelta: "Next: Aug 8", trendDirection: "up" as const },
  { title: "Profile Views", value: "56", trendDelta: "+12 this week", trendDirection: "up" as const },
  { title: "Saved Jobs", value: "9", trendDelta: "2 expiring soon", trendDirection: "neutral" as const },
];

export const MOCK_CANDIDATE_APPLICATIONS: JobApplication[] = [
  {
    id: "app-1",
    sn: 1,
    jobId: "job-1",
    jobTitle: "Backend Developer",
    companyName: "Bidur Systems",
    appliedDate: "Jul 28",
    location: "Kathmandu",
    salaryText: "Rs 85,000/mo",
    candidateName: "Sakhi",
    status: "screening",
  },
  {
    id: "app-2",
    sn: 2,
    jobId: "job-2",
    jobTitle: "Full Stack Engineer",
    companyName: "Khanepani Tech",
    appliedDate: "Jul 22",
    location: "Lalitpur",
    salaryText: "Rs 90,000/mo",
    candidateName: "Sakhi",
    status: "interview",
    statusCustomPill: "Interview Aug 8",
  },
  {
    id: "app-3",
    sn: 3,
    jobId: "job-3",
    jobTitle: "Laravel Developer",
    companyName: "Digital Pathshala",
    appliedDate: "Aug 1",
    location: "Remote",
    salaryText: "Rs 75,000/mo",
    candidateName: "Sakhi",
    status: "applied",
  },
  {
    id: "app-4",
    sn: 4,
    jobId: "job-4",
    jobTitle: "PHP Engineer",
    companyName: "Nepal Fintech",
    appliedDate: "Jul 15",
    location: "Kathmandu",
    salaryText: "Rs 70,000/mo",
    candidateName: "Sakhi",
    status: "not selected",
  },
  {
    id: "app-5",
    sn: 5,
    jobId: "job-5",
    jobTitle: "Senior PHP Developer",
    companyName: "CloudNP",
    appliedDate: "Jun 30",
    location: "Remote",
    salaryText: "Rs 95,000/mo",
    candidateName: "Sakhi",
    status: "offer",
  },
  {
    id: "app-6",
    sn: 6,
    jobId: "job-6",
    jobTitle: "REST API Developer",
    companyName: "Softworks Nepal",
    appliedDate: "Jun 20",
    location: "Kathmandu",
    salaryText: "Rs 80,000/mo",
    candidateName: "Sakhi",
    status: "screening",
  },
  {
    id: "app-7",
    sn: 7,
    jobId: "job-7",
    jobTitle: "Backend Lead",
    companyName: "Apex Digital",
    appliedDate: "Jun 12",
    location: "Lalitpur",
    salaryText: "Rs 1,00,000/mo",
    candidateName: "Sakhi",
    status: "rejected",
  },
  {
    id: "app-8",
    sn: 8,
    jobId: "job-8",
    jobTitle: "Laravel Backend Engineer",
    companyName: "WebTech Asia",
    appliedDate: "May 29",
    location: "Remote",
    salaryText: "Rs 88,000/mo",
    candidateName: "Sakhi",
    status: "applied",
  },
  {
    id: "app-9",
    sn: 9,
    jobId: "job-9",
    jobTitle: "Junior Backend Developer",
    companyName: "TechHub Nepal",
    appliedDate: "May 15",
    location: "Kathmandu",
    salaryText: "Rs 65,000/mo",
    candidateName: "Sakhi",
    status: "not selected",
  },
  {
    id: "app-10",
    sn: 10,
    jobId: "job-10",
    jobTitle: "Microservices Architect",
    companyName: "InfraCloud",
    appliedDate: "May 02",
    location: "Remote",
    salaryText: "Rs 1,10,000/mo",
    candidateName: "Sakhi",
    status: "applied",
  },
  {
    id: "app-11",
    sn: 11,
    jobId: "job-11",
    jobTitle: "API Integrator",
    companyName: "PaySwift",
    appliedDate: "Apr 20",
    location: "Kathmandu",
    salaryText: "Rs 82,000/mo",
    candidateName: "Sakhi",
    status: "screening",
  },
  {
    id: "app-12",
    sn: 12,
    jobId: "job-12",
    jobTitle: "Full Stack PHP Dev",
    companyName: "ByteLabs",
    appliedDate: "Apr 10",
    location: "Lalitpur",
    salaryText: "Rs 90,000/mo",
    candidateName: "Sakhi",
    status: "rejected",
  },
  {
    id: "app-13",
    sn: 13,
    jobId: "job-13",
    jobTitle: "Database Administrator",
    companyName: "DataGrid Systems",
    appliedDate: "Mar 28",
    location: "Kathmandu",
    salaryText: "Rs 95,000/mo",
    candidateName: "Sakhi",
    status: "applied",
  },
  {
    id: "app-14",
    sn: 14,
    jobId: "job-14",
    jobTitle: "Senior Software Engineer",
    companyName: "Everest Tech",
    appliedDate: "Mar 15",
    location: "Remote",
    salaryText: "Rs 1,05,000/mo",
    candidateName: "Sakhi",
    status: "offer",
  },
];

export const MOCK_RECOMMENDED_JOBS = [
  {
    id: "rec-1",
    title: "Backend Engineer",
    company: "Yeti Cloud",
    location: "Kathmandu (Hybrid)",
    salaryText: "Rs 85,000 - 1,05,000/mo",
    matchPercentage: 92,
  },
  {
    id: "rec-2",
    title: "Laravel API Dev",
    company: "Himal Softworks",
    location: "Remote (Nepal)",
    salaryText: "Rs 78,000 - 95,000/mo",
    matchPercentage: 86,
  },
];

export const MOCK_CANDIDATE_INTERVIEWS: Interview[] = [
  {
    id: "c-int-1",
    companyName: "Khanepani Tech",
    candidateName: "Sakhi",
    jobTitle: "Full Stack Engineer",
    type: "Technical Round 2",
    dateText: "Aug 8, 2:00 PM (Google Meet)",
    locationOrUrl: "Google Meet",
  },
  {
    id: "c-int-2",
    companyName: "CloudNP",
    candidateName: "Sakhi",
    jobTitle: "Senior PHP Developer",
    type: "HR / Offer Discussion",
    dateText: "Aug 11, 11:30 AM (Phone)",
    locationOrUrl: "Phone",
  },
];

export const MOCK_SKILL_GAPS: SkillGap[] = [
  { skill: "Docker", status: "missing" },
  { skill: "MySQL", status: "have" },
  { skill: "AWS Basics", status: "missing" },
];

export const MOCK_CANDIDATE_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif-1",
    type: "mail",
    message: "Khanepani Tech moved you to Interview",
    timeAgo: "2h ago",
  },
  {
    id: "notif-2",
    type: "view",
    message: "Your profile was viewed by CloudNP",
    timeAgo: "1d ago",
  },
  {
    id: "notif-3",
    type: "alert",
    message: "2 new job alerts match 'Laravel'",
    timeAgo: "2d ago",
  },
];
