import {
  JobApplication,
  Interview,
  SkillGap,
  AppNotification,
  ApplicationTimelineStep,
  InterviewDetail,
  JobMatchDetail,
  SkillSuggestion,
  ResumeVersion,
  CoverLetter,
  SavedJobCollection,
  ApplicationNote,
  FollowUpReminder,
  ProfileAnalytics,
  QuickApplyJob,
} from "../types";

export const MOCK_CANDIDATE_PROFILE = {
  name: "Sakhi",
  roleHeadline: "Backend Developer",
  skillsMeta: "Laravel, PHP, MySQL — 3 yrs experience — expects Rs 90,000/mo",
  isOpenToWork: true,
  completenessPercent: 72,
  completionHint: "Add 2 skills and a project to reach 90%",
  avatarText: "SK",
};

export const MOCK_CANDIDATE_KPIS = [
  {
    title: "Applications",
    value: "14",
    trendDelta: "3 active",
    trendDirection: "up" as const,
  },
  {
    title: "Interviews Scheduled",
    value: "3",
    trendDelta: "Next: Aug 8",
    trendDirection: "up" as const,
  },
  {
    title: "Profile Views",
    value: "56",
    trendDelta: "+12 this week",
    trendDirection: "up" as const,
  },
  {
    title: "Saved Jobs",
    value: "9",
    trendDelta: "2 expiring soon",
    trendDirection: "neutral" as const,
  },
];

export const MOCK_CANDIDATE_APPLICATIONS: JobApplication[] = [
  {
    id: "app-1",
    sn: 1,
    jobId: "job-1",
    jobTitle: "Backend Developer",
    companyName: "Bidur Systems",
    appliedDate: "Jul 28",
    location: "Kathmandu",
    salaryText: "Rs 85,000/mo",
    candidateName: "Sakhi",
    status: "screening",
  },
  {
    id: "app-2",
    sn: 2,
    jobId: "job-2",
    jobTitle: "Full Stack Engineer",
    companyName: "Khanepani Tech",
    appliedDate: "Jul 22",
    location: "Lalitpur",
    salaryText: "Rs 90,000/mo",
    candidateName: "Sakhi",
    status: "interview",
    statusCustomPill: "Interview Aug 8",
  },
  {
    id: "app-3",
    sn: 3,
    jobId: "job-3",
    jobTitle: "Laravel Developer",
    companyName: "Digital Pathshala",
    appliedDate: "Aug 1",
    location: "Remote",
    salaryText: "Rs 75,000/mo",
    candidateName: "Sakhi",
    status: "applied",
  },
  {
    id: "app-4",
    sn: 4,
    jobId: "job-4",
    jobTitle: "PHP Engineer",
    companyName: "Nepal Fintech",
    appliedDate: "Jul 15",
    location: "Kathmandu",
    salaryText: "Rs 70,000/mo",
    candidateName: "Sakhi",
    status: "not selected",
  },
  {
    id: "app-5",
    sn: 5,
    jobId: "job-5",
    jobTitle: "Senior PHP Developer",
    companyName: "CloudNP",
    appliedDate: "Jun 30",
    location: "Remote",
    salaryText: "Rs 95,000/mo",
    candidateName: "Sakhi",
    status: "offer",
  },
  {
    id: "app-6",
    sn: 6,
    jobId: "job-6",
    jobTitle: "REST API Developer",
    companyName: "Softworks Nepal",
    appliedDate: "Jun 20",
    location: "Kathmandu",
    salaryText: "Rs 80,000/mo",
    candidateName: "Sakhi",
    status: "screening",
  },
  {
    id: "app-7",
    sn: 7,
    jobId: "job-7",
    jobTitle: "Backend Lead",
    companyName: "Apex Digital",
    appliedDate: "Jun 12",
    location: "Lalitpur",
    salaryText: "Rs 1,00,000/mo",
    candidateName: "Sakhi",
    status: "rejected",
  },
  {
    id: "app-8",
    sn: 8,
    jobId: "job-8",
    jobTitle: "Laravel Backend Engineer",
    companyName: "WebTech Asia",
    appliedDate: "May 29",
    location: "Remote",
    salaryText: "Rs 88,000/mo",
    candidateName: "Sakhi",
    status: "applied",
  },
  {
    id: "app-9",
    sn: 9,
    jobId: "job-9",
    jobTitle: "Junior Backend Developer",
    companyName: "TechHub Nepal",
    appliedDate: "May 15",
    location: "Kathmandu",
    salaryText: "Rs 65,000/mo",
    candidateName: "Sakhi",
    status: "not selected",
  },
  {
    id: "app-10",
    sn: 10,
    jobId: "job-10",
    jobTitle: "Microservices Architect",
    companyName: "InfraCloud",
    appliedDate: "May 02",
    location: "Remote",
    salaryText: "Rs 1,10,000/mo",
    candidateName: "Sakhi",
    status: "applied",
  },
  {
    id: "app-11",
    sn: 11,
    jobId: "job-11",
    jobTitle: "API Integrator",
    companyName: "PaySwift",
    appliedDate: "Apr 20",
    location: "Kathmandu",
    salaryText: "Rs 82,000/mo",
    candidateName: "Sakhi",
    status: "screening",
  },
  {
    id: "app-12",
    sn: 12,
    jobId: "job-12",
    jobTitle: "Full Stack PHP Dev",
    companyName: "ByteLabs",
    appliedDate: "Apr 10",
    location: "Lalitpur",
    salaryText: "Rs 90,000/mo",
    candidateName: "Sakhi",
    status: "rejected",
  },
  {
    id: "app-13",
    sn: 13,
    jobId: "job-13",
    jobTitle: "Database Administrator",
    companyName: "DataGrid Systems",
    appliedDate: "Mar 28",
    location: "Kathmandu",
    salaryText: "Rs 95,000/mo",
    candidateName: "Sakhi",
    status: "applied",
  },
  {
    id: "app-14",
    sn: 14,
    jobId: "job-14",
    jobTitle: "Senior Software Engineer",
    companyName: "Everest Tech",
    appliedDate: "Mar 15",
    location: "Remote",
    salaryText: "Rs 1,05,000/mo",
    candidateName: "Sakhi",
    status: "offer",
  },
];

export const MOCK_RECOMMENDED_JOBS = [
  {
    id: "rec-1",
    title: "Backend Engineer",
    company: "Yeti Cloud",
    location: "Kathmandu (Hybrid)",
    salaryText: "Rs 85,000 - 1,05,000/mo",
    matchPercentage: 92,
  },
  {
    id: "rec-2",
    title: "Laravel API Dev",
    company: "Himal Softworks",
    location: "Remote (Nepal)",
    salaryText: "Rs 78,000 - 95,000/mo",
    matchPercentage: 86,
  },
];

export const MOCK_CANDIDATE_INTERVIEWS: Interview[] = [
  {
    id: "c-int-1",
    companyName: "Khanepani Tech",
    candidateName: "Sakhi",
    jobTitle: "Full Stack Engineer",
    type: "Technical Round 2",
    dateText: "Aug 8, 2:00 PM (Google Meet)",
    locationOrUrl: "Google Meet",
  },
  {
    id: "c-int-2",
    companyName: "CloudNP",
    candidateName: "Sakhi",
    jobTitle: "Senior PHP Developer",
    type: "HR / Offer Discussion",
    dateText: "Aug 11, 11:30 AM (Phone)",
    locationOrUrl: "Phone",
  },
];

export const MOCK_SKILL_GAPS: SkillGap[] = [
  { skill: "Docker", status: "missing" },
  { skill: "MySQL", status: "have" },
  { skill: "AWS Basics", status: "missing" },
];

export const MOCK_CANDIDATE_NOTIFICATIONS: AppNotification[] = [
  {
    id: "notif-1",
    type: "mail",
    message: "Khanepani Tech moved you to Interview",
    timeAgo: "2h ago",
  },
  {
    id: "notif-2",
    type: "view",
    message: "Your profile was viewed by CloudNP",
    timeAgo: "1d ago",
  },
  {
    id: "notif-3",
    type: "alert",
    message: "2 new job alerts match 'Laravel'",
    timeAgo: "2d ago",
  },
];

// Application timelines keyed by applicationId
export const MOCK_APPLICATION_TIMELINES: Record<
  string,
  ApplicationTimelineStep[]
> = {
  "app-1": [
    {
      stage: "applied",
      label: "Applied",
      date: "Jul 28",
      completed: true,
      active: false,
    },
    {
      stage: "screening",
      label: "Screening",
      date: "Aug 1",
      note: "Resume shortlisted",
      completed: false,
      active: true,
    },
    { stage: "interview", label: "Interview", completed: false, active: false },
    { stage: "offer", label: "Offer", completed: false, active: false },
    { stage: "hired", label: "Hired", completed: false, active: false },
  ],
  "app-2": [
    {
      stage: "applied",
      label: "Applied",
      date: "Jul 22",
      completed: true,
      active: false,
    },
    {
      stage: "screening",
      label: "Screening",
      date: "Jul 25",
      note: "Phone screen passed",
      completed: true,
      active: false,
    },
    {
      stage: "interview",
      label: "Interview",
      date: "Aug 8",
      note: "Technical Round 2 scheduled",
      completed: false,
      active: true,
    },
    { stage: "offer", label: "Offer", completed: false, active: false },
    { stage: "hired", label: "Hired", completed: false, active: false },
  ],
  "app-5": [
    {
      stage: "applied",
      label: "Applied",
      date: "Jun 30",
      completed: true,
      active: false,
    },
    {
      stage: "screening",
      label: "Screening",
      date: "Jul 3",
      completed: true,
      active: false,
    },
    {
      stage: "interview",
      label: "Interview",
      date: "Jul 10",
      completed: true,
      active: false,
    },
    {
      stage: "offer",
      label: "Offer",
      date: "Aug 5",
      note: "Offer letter sent — Rs 95,000/mo",
      completed: false,
      active: true,
    },
    { stage: "hired", label: "Hired", completed: false, active: false },
  ],
  "app-7": [
    {
      stage: "applied",
      label: "Applied",
      date: "Jun 12",
      completed: true,
      active: false,
    },
    {
      stage: "screening",
      label: "Screening",
      date: "Jun 15",
      completed: true,
      active: false,
    },
    {
      stage: "interview",
      label: "Interview",
      date: "Jun 20",
      completed: true,
      active: false,
    },
    { stage: "offer", label: "Offer", completed: true, active: false },
    {
      stage: "rejected",
      label: "Rejected",
      date: "Jul 1",
      note: "Position filled internally",
      completed: true,
      active: true,
    },
  ],
};

export const MOCK_INTERVIEW_DETAILS: InterviewDetail[] = [
  {
    id: "int-d-1",
    applicationId: "app-2",
    companyName: "Khanepani Tech",
    jobTitle: "Full Stack Engineer",
    round: "Technical Round 2",
    date: "Aug 8, 2026",
    time: "2:00 PM",
    meetLink: "https://meet.google.com/abc-defg-hij",
    interviewerName: "Arjun Sharma",
    interviewerRole: "Lead Engineer",
    prepNotes:
      "Review system design patterns, prepare for a 45-min live coding session on REST API design. Bring questions about the tech stack.",
    reminderSet: true,
    status: "upcoming",
  },
  {
    id: "int-d-2",
    applicationId: "app-5",
    companyName: "CloudNP",
    jobTitle: "Senior PHP Developer",
    round: "HR / Offer Discussion",
    date: "Aug 11, 2026",
    time: "11:30 AM",
    meetLink: undefined,
    interviewerName: "Priya Thapa",
    interviewerRole: "HR Manager",
    prepNotes:
      "Discuss salary expectations. Current offer: Rs 95,000. Target: Rs 1,05,000. Mention competing offer from Everest Tech.",
    reminderSet: false,
    status: "upcoming",
  },
  {
    id: "int-d-3",
    applicationId: "app-7",
    companyName: "Apex Digital",
    jobTitle: "Backend Lead",
    round: "Final Round",
    date: "Jun 20, 2026",
    time: "3:00 PM",
    interviewerName: "Bikash Rai",
    interviewerRole: "CTO",
    prepNotes: "Leadership questions, team management experience.",
    reminderSet: false,
    status: "completed",
  },
  {
    id: "int-d-4",
    applicationId: "app-1",
    companyName: "Bidur Systems",
    jobTitle: "Backend Developer",
    round: "Initial Screening",
    date: "Aug 20, 2026",
    time: "10:00 AM",
    meetLink: "https://meet.google.com/xyz-lmno-pqr",
    interviewerName: "Sunil KC",
    interviewerRole: "HR Manager",
    prepNotes: "Prepare a short self-introduction. Review Laravel project examples.",
    reminderSet: false,
    status: "upcoming",
  },
  {
    id: "int-d-5",
    applicationId: "app-6",
    companyName: "Softworks Nepal",
    jobTitle: "REST API Developer",
    round: "Technical Round 1",
    date: "Aug 25, 2026",
    time: "1:00 PM",
    meetLink: "https://meet.google.com/def-ghij-klm",
    interviewerName: "Ramesh Adhikari",
    interviewerRole: "Senior Engineer",
    prepNotes: "Focus on REST API design patterns and PHP best practices. Be ready for a take-home coding task.",
    reminderSet: true,
    status: "upcoming",
  },
  {
    id: "int-d-6",
    applicationId: "app-14",
    companyName: "Everest Tech",
    jobTitle: "Senior Software Engineer",
    round: "Culture Fit Interview",
    date: "Sep 3, 2026",
    time: "3:30 PM",
    meetLink: "https://meet.google.com/stu-vwxy-z12",
    interviewerName: "Nisha Karki",
    interviewerRole: "People Ops Lead",
    prepNotes: "Prepare 3 stories about working in teams. Research Everest Tech culture values on their website.",
    reminderSet: false,
    status: "upcoming",
  },
];

export const MOCK_JOB_MATCHES: JobMatchDetail[] = [
  {
    jobId: "rec-1",
    jobTitle: "Backend Engineer",
    companyName: "Yeti Cloud",
    overallMatch: 92,
    matchedSkills: ["Laravel", "PHP", "MySQL", "REST APIs", "Git"],
    missingSkills: ["Docker", "Redis"],
    salaryMatch: {
      candidate: 90000,
      jobMin: 85000,
      jobMax: 105000,
      match: true,
    },
    locationMatch: true,
    experienceMatch: true,
    experienceNote: "3 yrs matches requirement of 2–5 yrs",
  },
  {
    jobId: "rec-2",
    jobTitle: "Laravel API Dev",
    companyName: "Himal Softworks",
    overallMatch: 86,
    matchedSkills: ["Laravel", "PHP", "REST APIs"],
    missingSkills: ["TypeScript", "GraphQL"],
    salaryMatch: {
      candidate: 90000,
      jobMin: 78000,
      jobMax: 95000,
      match: true,
    },
    locationMatch: true,
    experienceMatch: true,
    experienceNote: "3 yrs matches requirement of 2–4 yrs",
  },
];

export const MOCK_SKILL_SUGGESTIONS: SkillSuggestion[] = [
  {
    skill: "Docker",
    reason: "Required in 6 of your saved/applied jobs",
    priority: "high",
    learnUrl: "https://docs.docker.com/get-started/",
  },
  {
    skill: "AWS Basics",
    reason: "Mentioned in 4 job descriptions you applied to",
    priority: "high",
    learnUrl: "https://aws.amazon.com/training/",
  },
  {
    skill: "TypeScript",
    reason: "Recommended for senior roles — 3 matches",
    priority: "medium",
    learnUrl: "https://www.typescriptlang.org/docs/",
  },
  {
    skill: "React",
    reason: "Full stack roles prefer React knowledge",
    priority: "medium",
  },
  {
    skill: "Redis",
    reason: "Listed as a plus in 2 backend job posts",
    priority: "low",
  },
  {
    skill: "GraphQL",
    reason: "Emerging preference in API-focused roles",
    priority: "low",
  },
];

export const MOCK_RESUME_VERSIONS: ResumeVersion[] = [
  {
    id: "rv-1",
    label: "Backend Resume",
    fileName: "sakhi_backend_resume_v3.pdf",
    targetRole: "Backend Developer",
    uploadedDate: "Aug 1, 2026",
    isDefault: true,
    size: "284 KB",
  },
  {
    id: "rv-2",
    label: "Full Stack Resume",
    fileName: "sakhi_fullstack_resume.pdf",
    targetRole: "Full Stack Engineer",
    uploadedDate: "Jul 15, 2026",
    isDefault: false,
    size: "310 KB",
  },
  {
    id: "rv-3",
    label: "Remote Jobs Resume",
    fileName: "sakhi_remote_optimized.pdf",
    targetRole: "Remote Backend Dev",
    uploadedDate: "Jun 20, 2026",
    isDefault: false,
    size: "268 KB",
  },
  {
    id: "rv-4",
    label: "Senior Role Resume",
    fileName: "sakhi_senior_lead.pdf",
    targetRole: "Backend Lead / Architect",
    uploadedDate: "Jun 5, 2026",
    isDefault: false,
    size: "295 KB",
  },
];

export const MOCK_COVER_LETTERS: CoverLetter[] = [
  {
    id: "cl-1",
    jobTitle: "Backend Engineer",
    companyName: "Yeti Cloud",
    createdDate: "Aug 2, 2026",
    applicationId: "app-1",
    content: `Dear Hiring Team at Yeti Cloud,

I am writing to express my strong interest in the Backend Engineer position. With 3+ years of hands-on experience building scalable REST APIs and microservices using Laravel and PHP, I am confident I can contribute meaningfully to your engineering team.

At TechCraft Nepal, I designed and maintained a fintech payment gateway handling thousands of daily transactions, improving response time by 40% through Redis caching and query optimization.

I am particularly excited about Yeti Cloud's mission to modernize Nepal's cloud infrastructure and would love to bring my expertise in backend systems to your team.

Thank you for your time and consideration.

Best regards,
Sakhi Karki`,
  },
  {
    id: "cl-2",
    jobTitle: "Senior PHP Developer",
    companyName: "CloudNP",
    createdDate: "Jul 18, 2026",
    applicationId: "app-5",
    content: `Dear CloudNP Team,

I am excited to apply for the Senior PHP Developer role. My background in Laravel, REST API design, and database optimization aligns well with your requirements for a senior backend engineer.

I have led backend development for multiple production systems, including an event-driven notification service processing 10,000+ requests per second.

I look forward to discussing how I can contribute to CloudNP's growth.

Sincerely,
Sakhi Karki`,
  },
];

export const MOCK_SAVED_COLLECTIONS: SavedJobCollection[] = [
  {
    id: "col-1",
    name: "Apply Soon",
    icon: "clock",
    color: "amber",
    jobs: [
      {
        id: "s-1",
        title: "Backend Engineer",
        company: "Yeti Cloud",
        location: "Kathmandu",
        salaryText: "Rs 85k–1.05L",
        expiresIn: "3 days",
      },
      {
        id: "s-2",
        title: "PHP Lead",
        company: "NepSoft",
        location: "Lalitpur",
        salaryText: "Rs 95k–1.1L",
        expiresIn: "5 days",
      },
    ],
  },
  {
    id: "col-2",
    name: "Remote Jobs",
    icon: "globe",
    color: "blue",
    jobs: [
      {
        id: "s-3",
        title: "Laravel API Dev",
        company: "Himal Softworks",
        location: "Remote",
        salaryText: "Rs 78k–95k",
      },
      {
        id: "s-4",
        title: "Backend Developer",
        company: "InfraCloud",
        location: "Remote",
        salaryText: "Rs 90k–1.1L",
      },
      {
        id: "s-5",
        title: "Node.js Engineer",
        company: "ByteWave",
        location: "Remote",
        salaryText: "Rs 85k–1.05L",
      },
    ],
  },
  {
    id: "col-3",
    name: "High Salary",
    icon: "trending-up",
    color: "green",
    jobs: [
      {
        id: "s-6",
        title: "Microservices Architect",
        company: "Apex Digital",
        location: "Kathmandu",
        salaryText: "Rs 1.2L–1.5L",
      },
      {
        id: "s-7",
        title: "Backend Lead",
        company: "TechPeak Nepal",
        location: "Lalitpur",
        salaryText: "Rs 1.1L–1.3L",
      },
    ],
  },
  {
    id: "col-4",
    name: "Dream Companies",
    icon: "star",
    color: "purple",
    jobs: [
      {
        id: "s-8",
        title: "Senior Engineer",
        company: "Everest Tech",
        location: "Remote",
        salaryText: "Rs 1.05L–1.2L",
      },
    ],
  },
];

export const MOCK_APPLICATION_NOTES: ApplicationNote[] = [
  {
    applicationId: "app-2",
    recruiterName: "Maya Gurung",
    interviewFeedback:
      "Good communication. Needs to revise system design knowledge.",
    followUpDate: "2026-08-10",
    salaryDiscussion: "Budget is Rs 88k–95k. Can negotiate.",
    privateNotes:
      "Maya was friendly — ask about remote flex days in next call.",
    lastUpdated: "Aug 5, 2026",
  },
  {
    applicationId: "app-5",
    recruiterName: "Priya Thapa",
    interviewFeedback: "Strong technical round. Offer incoming.",
    followUpDate: "2026-08-12",
    salaryDiscussion: "Offered Rs 95k. Targeting Rs 1,05,000.",
    privateNotes: "CloudNP has flexible WFH policy. Strong culture fit.",
    lastUpdated: "Aug 6, 2026",
  },
  {
    applicationId: "app-1",
    recruiterName: "Sunil KC",
    privateNotes: "Bidur Systems is growing fast — good long-term potential.",
    lastUpdated: "Aug 2, 2026",
  },
];

export const MOCK_FOLLOWUP_REMINDERS: FollowUpReminder[] = [
  {
    applicationId: "app-8",
    jobTitle: "Laravel Backend Engineer",
    companyName: "WebTech Asia",
    appliedDate: "May 29",
    daysSince: 74,
    status: "applied",
    suggestedAction: "Send a polite follow-up email to the hiring team.",
  },
  {
    applicationId: "app-3",
    jobTitle: "Laravel Developer",
    companyName: "Digital Pathshala",
    appliedDate: "Aug 1",
    daysSince: 10,
    status: "applied",
    suggestedAction: "Check the job portal for any status updates.",
  },
  {
    applicationId: "app-13",
    jobTitle: "Database Administrator",
    companyName: "DataGrid Systems",
    appliedDate: "Mar 28",
    daysSince: 136,
    status: "applied",
    suggestedAction:
      "Application may be stale — consider reapplying or withdrawing.",
  },
];

export const MOCK_PROFILE_ANALYTICS: ProfileAnalytics = {
  totalViews: 56,
  viewsThisWeek: 12,
  searchAppearances: 143,
  profileStrength: 72,
  topSkillsFound: ["Laravel", "PHP", "MySQL", "REST APIs", "Backend"],
  recentViewers: [
    { company: "Yeti Cloud", role: "Tech Recruiter", timeAgo: "2h ago" },
    { company: "CloudNP", role: "HR Manager", timeAgo: "1d ago" },
    { company: "Himal Softworks", role: "Engineering Lead", timeAgo: "2d ago" },
    { company: "InfraCloud", role: "CTO", timeAgo: "3d ago" },
    { company: "ByteLabs", role: "Recruiter", timeAgo: "4d ago" },
  ],
  weeklyViews: [
    { week: "Jul 7", views: 4 },
    { week: "Jul 14", views: 7 },
    { week: "Jul 21", views: 9 },
    { week: "Jul 28", views: 6 },
    { week: "Aug 4", views: 12 },
  ],
};

export const MOCK_QUICK_APPLY_JOBS: QuickApplyJob[] = [
  {
    id: "qa-1",
    title: "Backend Developer",
    company: "Yeti Cloud",
    location: "Kathmandu",
    workMode: "Hybrid",
    salaryText: "Rs 85k–1.05L",
    matchPercentage: 94,
    tags: ["Laravel", "PHP", "MySQL"],
    postedAgo: "2d ago",
  },
  {
    id: "qa-2",
    title: "Laravel API Developer",
    company: "Himal Softworks",
    location: "Remote",
    workMode: "Remote",
    salaryText: "Rs 80k–95k",
    matchPercentage: 89,
    tags: ["Laravel", "REST API", "Git"],
    postedAgo: "1d ago",
  },
  {
    id: "qa-3",
    title: "PHP Backend Engineer",
    company: "NepSoft Solutions",
    location: "Lalitpur",
    workMode: "On-site",
    salaryText: "Rs 75k–90k",
    matchPercentage: 85,
    tags: ["PHP", "MySQL", "Docker"],
    postedAgo: "3d ago",
  },
  {
    id: "qa-4",
    title: "Full Stack Developer",
    company: "TechHub Nepal",
    location: "Remote",
    workMode: "Remote",
    salaryText: "Rs 90k–1.1L",
    matchPercentage: 81,
    tags: ["Laravel", "React", "MySQL"],
    postedAgo: "5h ago",
  },
  {
    id: "qa-5",
    title: "Senior Backend Engineer",
    company: "CloudNP",
    location: "Kathmandu",
    workMode: "Hybrid",
    salaryText: "Rs 1L–1.2L",
    matchPercentage: 78,
    tags: ["PHP", "Redis", "AWS"],
    postedAgo: "1d ago",
  },
];
